"""post table update timestamp

Revision ID: a8a789bc593d
Revises: d04421b50f36
Create Date: 2020-03-10 00:32:57.362654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a789bc593d'
down_revision = 'd04421b50f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
